# Stage 1: Build Angular application
FROM node:16.20.2-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build -- --configuration=production

# Stage 2: Serve with Nginx
FROM nginx:1.25.3-alpine

RUN rm -rf /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d

COPY --from=builder /app/dist/progetto-laguna-fe /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]